Publishers:
  Facebook:
    ParentObject: '123456789012'
    AccessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  Telegram:
    Token: 'xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    ChatId: '@chatName'
  Viber:
    Token: 'xxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx'
    Avatar: 'https://icon-icons.com/icons2/1371/PNG/512/robot02_90810.png'
    Name: 'Bot name'

Sources:
  ED:
    Cities: ['Banatsko Veliko Selo', 'Kikinda']
